sudo: required

language: node_js

services:
- docker

node_js:
- "node"
before_install:
- docker-compose up -d
- docker-compose ps
- npm install -g typescript

script:
- npm run lint
- npm run test:full