# volume container to provide consistent storage.
postgres-data:
  image: sameersbn/postgresql:9.6-2
  command: /bin/true

# a postgres container for providing database access.
postgres:
  image: sameersbn/postgresql:9.6-2
  environment:
    - DB_USER=stratego
    - DB_PASS=supasecretpassword
    - DB_NAME=stratego,strategoWorld,testStratego,testStrategoWorld
  ports:
    - "5432:5432"
  volumes_from:
    - postgres-data
  command: -c "max_stack_depth=6MB"